/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VendorPricingRouteImport } from './routes/vendor-pricing'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeAVendorRouteImport } from './routes/become-a-vendor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorSubscriptionRouteImport } from './routes/vendor.subscription'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorPayoutsRouteImport } from './routes/vendor.payouts'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorOnboardingRouteImport } from './routes/vendor.onboarding'
import { Route as VendorImportsRouteImport } from './routes/vendor.imports'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as VendorProductsIndexRouteImport } from './routes/vendor.products.index'
import { Route as VendorOrdersIndexRouteImport } from './routes/vendor.orders.index'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as VendorOrdersIdRouteImport } from './routes/vendor.orders.$id'
import { Route as VendorProductsIdEditRouteImport } from './routes/vendor.products.$id.edit'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPricingRoute = VendorPricingRouteImport.update({
  id: '/vendor-pricing',
  path: '/vendor-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAVendorRoute = BecomeAVendorRouteImport.update({
  id: '/become-a-vendor',
  path: '/become-a-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSubscriptionRoute = VendorSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPayoutsRoute = VendorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOnboardingRoute = VendorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => VendorRoute,
} as any)
const VendorImportsRoute = VendorImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const VendorProductsIndexRoute = VendorProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorProductsRoute,
} as any)
const VendorOrdersIndexRoute = VendorOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VendorProductsRoute,
} as any)
const VendorOrdersIdRoute = VendorOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorOrdersRoute,
} as any)
const VendorProductsIdEditRoute = VendorProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => VendorProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendor-pricing': typeof VendorPricingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/imports': typeof VendorImportsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vendor-pricing': typeof VendorPricingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/imports': typeof VendorImportsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/orders': typeof VendorOrdersIndexRoute
  '/vendor/products': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-a-vendor': typeof BecomeAVendorRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendor-pricing': typeof VendorPricingRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/imports': typeof VendorImportsRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/orders': typeof VendorOrdersRouteWithChildren
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/products': typeof VendorProductsRouteWithChildren
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/subscription': typeof VendorSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/vendor/orders/$id': typeof VendorOrdersIdRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/orders/': typeof VendorOrdersIndexRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
  '/vendor/products/$id/edit': typeof VendorProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/become-a-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/deals'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/role-select'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/trending'
    | '/vendor'
    | '/vendor-pricing'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/integrations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/vendors'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/store/$slug'
    | '/vendor/analytics'
    | '/vendor/imports'
    | '/vendor/onboarding'
    | '/vendor/orders'
    | '/vendor/payouts'
    | '/vendor/products'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin/'
    | '/vendor/'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/vendor/orders/'
    | '/vendor/products/'
    | '/vendor/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/become-a-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/deals'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/role-select'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/trending'
    | '/vendor-pricing'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/integrations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/vendors'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/store/$slug'
    | '/vendor/analytics'
    | '/vendor/imports'
    | '/vendor/onboarding'
    | '/vendor/payouts'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin'
    | '/vendor'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/become-a-vendor'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/deals'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/role-select'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/terms'
    | '/trending'
    | '/vendor'
    | '/vendor-pricing'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/disputes'
    | '/admin/integrations'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/vendors'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$slug'
    | '/store/$slug'
    | '/vendor/analytics'
    | '/vendor/imports'
    | '/vendor/onboarding'
    | '/vendor/orders'
    | '/vendor/payouts'
    | '/vendor/products'
    | '/vendor/settings'
    | '/vendor/subscription'
    | '/admin/'
    | '/vendor/'
    | '/vendor/orders/$id'
    | '/vendor/products/new'
    | '/vendor/orders/'
    | '/vendor/products/'
    | '/vendor/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeAVendorRoute: typeof BecomeAVendorRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CouponsRoute: typeof CouponsRoute
  DealsRoute: typeof DealsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  RoleSelectRoute: typeof RoleSelectRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  VendorRoute: typeof VendorRouteWithChildren
  VendorPricingRoute: typeof VendorPricingRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-pricing': {
      id: '/vendor-pricing'
      path: '/vendor-pricing'
      fullPath: '/vendor-pricing'
      preLoaderRoute: typeof VendorPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-vendor': {
      id: '/become-a-vendor'
      path: '/become-a-vendor'
      fullPath: '/become-a-vendor'
      preLoaderRoute: typeof BecomeAVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/subscription': {
      id: '/vendor/subscription'
      path: '/subscription'
      fullPath: '/vendor/subscription'
      preLoaderRoute: typeof VendorSubscriptionRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/payouts': {
      id: '/vendor/payouts'
      path: '/payouts'
      fullPath: '/vendor/payouts'
      preLoaderRoute: typeof VendorPayoutsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/onboarding': {
      id: '/vendor/onboarding'
      path: '/onboarding'
      fullPath: '/vendor/onboarding'
      preLoaderRoute: typeof VendorOnboardingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/imports': {
      id: '/vendor/imports'
      path: '/imports'
      fullPath: '/vendor/imports'
      preLoaderRoute: typeof VendorImportsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/products/': {
      id: '/vendor/products/'
      path: '/'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorProductsIndexRouteImport
      parentRoute: typeof VendorProductsRoute
    }
    '/vendor/orders/': {
      id: '/vendor/orders/'
      path: '/'
      fullPath: '/vendor/orders/'
      preLoaderRoute: typeof VendorOrdersIndexRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorProductsRoute
    }
    '/vendor/orders/$id': {
      id: '/vendor/orders/$id'
      path: '/$id'
      fullPath: '/vendor/orders/$id'
      preLoaderRoute: typeof VendorOrdersIdRouteImport
      parentRoute: typeof VendorOrdersRoute
    }
    '/vendor/products/$id/edit': {
      id: '/vendor/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/vendor/products/$id/edit'
      preLoaderRoute: typeof VendorProductsIdEditRouteImport
      parentRoute: typeof VendorProductsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface VendorOrdersRouteChildren {
  VendorOrdersIdRoute: typeof VendorOrdersIdRoute
  VendorOrdersIndexRoute: typeof VendorOrdersIndexRoute
}

const VendorOrdersRouteChildren: VendorOrdersRouteChildren = {
  VendorOrdersIdRoute: VendorOrdersIdRoute,
  VendorOrdersIndexRoute: VendorOrdersIndexRoute,
}

const VendorOrdersRouteWithChildren = VendorOrdersRoute._addFileChildren(
  VendorOrdersRouteChildren,
)

interface VendorProductsRouteChildren {
  VendorProductsNewRoute: typeof VendorProductsNewRoute
  VendorProductsIndexRoute: typeof VendorProductsIndexRoute
  VendorProductsIdEditRoute: typeof VendorProductsIdEditRoute
}

const VendorProductsRouteChildren: VendorProductsRouteChildren = {
  VendorProductsNewRoute: VendorProductsNewRoute,
  VendorProductsIndexRoute: VendorProductsIndexRoute,
  VendorProductsIdEditRoute: VendorProductsIdEditRoute,
}

const VendorProductsRouteWithChildren = VendorProductsRoute._addFileChildren(
  VendorProductsRouteChildren,
)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorImportsRoute: typeof VendorImportsRoute
  VendorOnboardingRoute: typeof VendorOnboardingRoute
  VendorOrdersRoute: typeof VendorOrdersRouteWithChildren
  VendorPayoutsRoute: typeof VendorPayoutsRoute
  VendorProductsRoute: typeof VendorProductsRouteWithChildren
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorSubscriptionRoute: typeof VendorSubscriptionRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorImportsRoute: VendorImportsRoute,
  VendorOnboardingRoute: VendorOnboardingRoute,
  VendorOrdersRoute: VendorOrdersRouteWithChildren,
  VendorPayoutsRoute: VendorPayoutsRoute,
  VendorProductsRoute: VendorProductsRouteWithChildren,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorSubscriptionRoute: VendorSubscriptionRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeAVendorRoute: BecomeAVendorRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CouponsRoute: CouponsRoute,
  DealsRoute: DealsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  RoleSelectRoute: RoleSelectRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  VendorRoute: VendorRouteWithChildren,
  VendorPricingRoute: VendorPricingRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
