-- Align RLS INSERT checks with the states generated by the consolidated
-- server-authoritative triggers. Browser callers still cannot self-approve:
-- the BEFORE triggers normalize/reject requested states before RLS WITH CHECK.

DROP POLICY IF EXISTS "Users can create their own vendor record"
ON public.vendors;

CREATE POLICY "Users can create their own vendor record"
ON public.vendors
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
  AND status IN (
    'pending'::public.vendor_status,
    'active'::public.vendor_status
  )
);

DROP POLICY IF EXISTS "Vendors insert own products"
ON public.products;

CREATE POLICY "Vendors insert own products"
ON public.products
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.vendors AS v
    WHERE v.id = products.vendor_id
      AND v.user_id = auth.uid()
  )
  AND status IN (
    'draft'::public.product_status,
    'pending_review'::public.product_status,
    'active'::public.product_status
  )
);

CREATE OR REPLACE FUNCTION public.get_1lv_schema_version()
RETURNS text
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT '20261002110000';
$$;

REVOKE ALL ON FUNCTION public.get_1lv_schema_version()
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_1lv_schema_version()
TO service_role;
